export const CATEGORIES = {
    APS: "Anonymity for Personal Safety",
    CD: "Correctness of Data",
    CE: "Criminal Exploitation",
    DC: "Data Collection",
    DR: "Data Retention",
    DIT: "Digital Identity Theft",
    DSTP: "Data Sale to Third Parties",
    ESH: "Emotional/Social Harm",
    GLR: "Geo-location Risks",
    LC: "Loss of Control",
    LRPG: "Legal vs. Real Protection Gap",
    LT: "Lack of Transparency",
    MIC: "Mistrust in Companies",
    MPOT: "Managing Privacy Over Time",
    ODU: "Opacity of Data Use",
    PA: "Purpose Ambiguity",
    PD: "Physical Danger",
    RD: "Reputation Damage",
    SB: "Security Breaches",
    SE: "Social Engineering",
    ST: "Surveillance & Tracking",
    UDU: "Unauthorized Data Use"
};